{% set version = "0.4.3" %}
{% set hash_val = "78a157fbe0f52250e96e19ee769cd064" %}

package:
  name: resampy
  version: {{ version }}

source:
  fn: resampy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/resampy/resampy-{{ version }}.tar.gz
  md5: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.6
    - wheel >=0.29.0
    - importlib-resources

  run:
    - python >=3.6
    - numpy >=1.17.0
    - numba >=0.53
    - importlib-resources

test:
  imports:
    - resampy

about:
  home: https://github.com/bmcfee/resampy
  license: ISC
  summary: 'Efficient signal resampling'

extra:
  recipe-maintainers:
    - bmcfee
