{% set version = "0.4.3" %}
{% set hash_val = "78a157fbe0f52250e96e19ee769cd064" %}

package:
  name: resampy
  version: {{ version }}

source:
  fn: resampy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/resampy/resampy-{{ version }}.tar.gz
  md5: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - import_resources ; python_version < "3.9"
    - pip
    - python >=3.6
    - setuptools >=48
    - wheel >=0.29.0

  run:
    - python >=3.6
    - setuptools >=48 # necessary for pkg_resources at runtime
    - numpy >=1.17.0
    - numba >=0.53

test:
  imports:
    - resampy

about:
  home: https://github.com/bmcfee/resampy
  license: ISC
  summary: 'Efficient signal resampling'

extra:
  recipe-maintainers:
    - bmcfee
